---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
  labels:
    app: podinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.3
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfo
    spec:
      containers:
      - name: hooks
        image: aalpgiray/hooks:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1234
          name: http
          protocol: TCP
        command:
        - npm
        - run
        - start
        env:
        - name: PODINFO_UI_COLOR
          value: black
  
